name: registry_service

services:
  registry_service:
    build: .
    image: registry-service
    container_name: registry_container
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    ports:
      - "8000:8000"
    command: uv run main.py


