"""init

Revision ID: 1cd96b8fee10
Revises: 
Create Date: 2026-03-08 17:00:27.964257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cd96b8fee10'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('TransactionType', sa.Integer(), nullable=False),
    sa.Column('Data', sa.String(), nullable=False),
    sa.Column('Hash', sa.String(), nullable=False),
    sa.Column('Sign', sa.String(), nullable=False),
    sa.Column('SignerCert', sa.String(), nullable=False),
    sa.Column('TransactionTime', sa.DateTime(), nullable=False),
    sa.Column('Metadata', sa.String(), nullable=True),
    sa.Column('TransactionIn', sa.String(), nullable=True),
    sa.Column('TransactionOut', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
